server:
  port: 0
spring:
  application:
    name: user-ws
  devtools:
    restart.enable: true

eureka:
  instance:
    hostname: localhost
    port: 8010
  client:
    serviceUrl:
      defaultZone: http://${eureka.instance.hostname}:${eureka.instance.port}/eureka/
