server:
  port: ${PORT:0}
spring:
  application:
    name: user-ws
  devtools:
    restart.enable: true

eureka:
  instance:
    instance-id: ${spring.application.name}:${spring.application.instance_id:${random.value}}
    hostname: localhost
    port: 8010
  client:
    serviceUrl:
      defaultZone: http://${eureka.instance.hostname}:${eureka.instance.port}/eureka/
